# tasks file
---
- name: databases | create
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
  with_items: "{{ percona_server_databases_present }}"
  tags:
    - percona-server-databases-create

- name: databases | drop
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ percona_server_databases_absent }}"
  tags:
    - percona-server-databases-drop
